FindIt/Models/Entities/MainCategories.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FindIt.Models.Entities
{
    public class MainCategories
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public virtual ICollection<SubCategorie> SubCategorie { get; set; }
    }
}

FindIt/Controllers/MainCategorieController.cs
using FindIt.Models.Entities;
using FindIt.Models.Manager;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FindIt.Controllers
{
    public class MainCategorieController : Controller
    {
        // GET: Categorie
        public ActionResult Index()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        public ActionResult AddMainCategorie(MainCategories mainCategorie)
        {
          
            if (mainCategorie.Name != null)
            {
       //         if (ModelState.IsValid)
       //         {
                    //modifier une categorie
                    if (mainCategorie.Id != 0 && MainCategoriesManager.GetByName(mainCategorie.Name) == null)
                    {
                        MainCategoriesManager.Modify(mainCategorie);
                        ModelState.AddModelError("", "vous avez bien modifier la categorie "+mainCategorie.Name);
                        mainCategorie = null;
                        return View("Index", mainCategorie);
                    }
                    // verifier l'existence d'une categorie
                    if (MainCategoriesManager.GetByName(mainCategorie.Name) != null)
                    {
                        ModelState.AddModelError("", "cette categorie existe deja dans la base de donnees");
                        return View("Index", mainCategorie);
                    }
                    //ajout de categorie
                    MainCategoriesManager.Add(mainCategorie);
                    ModelState.AddModelError("", "la categorie a bien ete ajouter");
                    return View("Index");
        //        }
            }else if(mainCategorie.Id != 0){
                mainCategorie = MainCategoriesManager.GetById(mainCategorie.Id);
                ModelState.AddModelError("", "La categorie est pret a etre modifier");
                return View("Index", mainCategorie);
            }else{
                ModelState.AddModelError("", "Veuillez saisir une categorie de produit");
           //     return View(mainCategorie);
            }
            
            return View("Index", mainCategorie);
        }
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int idCategorie)
        {

            MainCategoriesManager.Delete(idCategorie);
            
            return View("Index");
        }
    }
    
}

FindIt/Views/MainCategorie/Index.cshtml
@using FindIt.Models.Entities
@using FindIt.Models.Manager

@model MainCategories
@{
    ViewBag.Title = "AddMainCategorie";
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<h2>Gestion des Categories primaire</h2>

@Html.ActionLink("Ajouter", "Index",new {id = 0})
@using (Html.BeginForm("AddMainCategorie", "MainCategorie"))
{

    @Html.ValidationSummary(true)
    @Html.HiddenFor(c => c.Id)
    
  //  @Html.TextBoxFor(c => c.Id)

    @Html.TextBoxFor(c => c.Name)

    <input type="submit" />
}

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Action</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (MainCategories mc in MainCategoriesManager.GetAll())
        {
            <tr>
                <td>@mc.Id</td>
                <td>@mc.Name</td>

                <td>@Html.ActionLink("Modifier", "AddMainCategorie", new { id = @mc.Id })</td>
                <td>@Html.ActionLink("Supprimer", "Delete", new { idCategorie = @mc.Id, id = 0 }, new { @class = "delete" })</td>

            </tr>
        }
    </tbody>

</table>
@section scripts{
    <script>
        $(document).ready(function () {
            $('.delete').click(function () {
                return confirm("Si vouz supprimer cette categorie vous allez supprimer tous les produits qui vont avec");
            });
        });
    </script>
}