FindIt/Models/Entities/Supplier.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FindIt.Models.Entities
{
    public class Supplier
    {
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }
        public string Description { get; set; }
        [Required]
        public int AddressId { get; set; }
        public virtual Address Address { get; set; }

        [Required]
        public string Phone { get; set; }

        [DisplayName("Contact Ressource")]
        public string ContactRessource { get; set; }
        
        [Required]
        [EmailAddress]
        public string Email { get; set; }
        public virtual ICollection<Product> Products { get; set; }

    }
}

FindIt/Controllers/AddressController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FindIt.Models;
using FindIt.Models.Entities;
using FindIt.Models.Manager;

namespace FindIt.Controllers
{
    [Authorize]
    public class AddressController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details(int id)
        {
            return View();
        }

        public ActionResult Create()
        {
            //Uri url = Request.UrlReferrer;
            // url.
            return View();
        }

        public ActionResult CreateAddressForUser(string UserId)
        {
            Address address = new Address();
            address.UserId = UserId;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Address newAddress)
        {
            int addId;
            if (ModelState.IsValid)
            {
                if (!AddressManager.ExistInDb(newAddress))
                {
                    AddressManager.Add(newAddress);
                    addId = newAddress.Id;
                }
                else
                {
                    addId = AddressManager.GetIDByData(newAddress);
                }
                return RedirectToAction("Create", "Supplier", new { id = addId });
            }
            else
            {
                return View(newAddress);
            }
        }

        public ActionResult Edit(int id, int supplierId)
        {
            Address address = AddressManager.GetById(id);
            address.SupplierId = supplierId;
            return View(address);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Address newAddress)
        {
            Supplier s = SupplierManager.GetById((int)newAddress.SupplierId.Value);
            if (ModelState.IsValid)
            {
                if (!AddressManager.ExistInDb(newAddress))
                {
                    AddressManager.Add(newAddress);
                    s.AddressId = newAddress.Id;
                    SupplierManager.Modify(s);
                }
                else
                {
                    s.AddressId = AddressManager.GetIDByData(newAddress);
                    SupplierManager.Modify(s);
                }
                return RedirectToAction("Index", "Supplier");
            }
            else
            {
                return View(newAddress);
            }
        }

        //Partial View for when Adding/Modifying Address of User/Supplier
        [AllowAnonymous]
        public ActionResult ProvinceView(int id)
        {
            ViewBag.countryId = id;
            return PartialView();
        }
    }
}

FindIt/Controllers/ProductController.cs
using FindIt.Models;
using FindIt.Models.Entities;
using FindIt.Models.Manager;
using FindIt.Models.Manager;
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace FindIt.Controllers
{
    [AllowAnonymous]
    public class ProductController : Controller
    {

        public ActionResult Delete3(int commentid, int produitid)
        {
            CommentManager.Delete(commentid);
            return RedirectToAction("Details", "product", new { id = produitid });
        }
        public ActionResult Products( int? page)
        {
            List<Product> allProduct = ProductManager.GetAll();
            int pageSize = 8;
            int pageNumber = (page ?? 1);
            return View(allProduct.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Index()
        {
            return View();
        }
        // GET: Produit
        //TODO A revoir remplacer la liste de categori par vue partial
        public ActionResult GetListCategoriePartialView()
        {
            List<MainCategories> listCategories = MainCategoriesManager.GetAll();
            return PartialView(listCategories);
        }


        public ActionResult GetProductByCategorieParitalView(int id, int? page)
        {
            List<Product> listProduct = ProductManager.GetByCategorieId(id);

            TempData["subCategories"] = SubCategorieManager.GetByIdCategorie(id);
            
            int pageSize = 8;
            int pageNumber = (page ?? 1);
            return View(listProduct.ToPagedList(pageNumber, pageSize));

        }
        public ActionResult GetProductBySubCategorieParitalView(int id)
        {
            List<Product> listProduct = ProductManager.GetByIdSubCategorie(id);
            if (listProduct != null)
            {
          //      SubCategorie sub = SubCategorieManager.GetById(listProduct.FirstOrDefault().SubCategorieID);
                SubCategorie sub = SubCategorieManager.GetById(id); 
                if(sub != null)
                    TempData["subCategories"] = SubCategorieManager.GetByIdCategorie(sub.MainCategoriesId);
            }
            return View("GetProductByCategorieParitalView", listProduct.ToPagedList( 1, 8));
        }
        // getAll Product by Categorie
        public ActionResult GetProductByCategorie(int id)
        {
            List<Product> listProduct = ProductManager.GetByCategorieId(id);
            TempData["subCategories"]
                = SubCategorieManager.GetByIdCategorie(id);
            return View("GetAllProduct", listProduct);
        }

        //getAll product by name or KeyWord

        public ActionResult GetProductByNameOrKeyWord(string name)
        {
            List<Product> listProduct = ProductManager.GetByNameOrKeyWord(name);
            return View("GetProductByNameOrKeyWord", listProduct);
        }


        public ActionResult GetAllProduct()
        {
            List<Product> allProduct = ProductManager.GetAll();
            return View(allProduct);
        }

        [Authorize(Roles="Admin,Employee,Buyer")]
        public ActionResult AddKeyWord(string key)
        {
            Keyword keyword = new Keyword { Name = key };
            int nb = KeywordManager.Add(keyword);
            if (nb > 0)
            {

                TempData["msg"] = "L'ajout est bien ajoute";
            }
            else
            {
                TempData["msg"] = "mot cle deja existe";
            }
            
            ViewBag.KeyWordList = KeywordManager.GetSelectList(null);
            return View();
        }

        [Authorize(Roles = "Admin,Employee,Buyer")]
        public ActionResult Edit(int id)
        {
            ViewBag.KeyWordList = KeywordManager.GetSelectList(null);
            ViewBag.SupplierList = SupplierManager.GetSelectList(null);
            ViewBag.SubCategorieList = SubCategorieManager.GetSelectList(null);
            Product product = ProductManager.GetById(id);
            if (product != null)
            {
                return View(product);
            }
            else
            {
                return RedirectToAction("GetAllProduct");
            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Product product, HttpPostedFileBase upload)
        {
            Product pro = ProductManager.GetById(product.Id); 
            if (ModelState.IsValid)
            {
                if (upload != null && upload.ContentLength > 0)
                {
                    File ff = pro.Files.Where(p => p.ProductId == pro.Id).FirstOrDefault();
                    if (pro.Files.Any(f => f.FileType == FileType.Avatar))
                    {

                        FileManager.Delete(ff);
                    }
                    var avatar = new File
                    {
                        FileName = System.IO.Path.GetFileName(upload.FileName),
                        FileType = FileType.Avatar,
                        ContentType = upload.ContentType
                    };
                    using (var reader = new System.IO.BinaryReader(upload.InputStream))
                    {
                        avatar.Content = reader.ReadBytes(upload.ContentLength);
                    }
                    product.Files = new List<File> { avatar };
                }
                ProductManager.Edit(product);
                ModelState.Clear();
                return RedirectToAction("Products");
            }
            else
            {
                ViewBag.KeyWordList = KeywordManager.GetSelectList(null);
                ViewBag.SupplierList = SupplierManager.GetSelectList(null);
                ViewBag.SubCategorieList = SubCategorieManager.GetSelectList(null);
                return View(product);
            }
        }

        [Authorize(Roles = "Admin,Employee,Buyer")]
        public ActionResult Delete(int id)
        {
            ProductManager.Delete(id);
            return RedirectToAction("GetAllProduct");
        }


        public ActionResult Details(int id)
        {
            Product product = ProductManager.GetById(id);
            if (product != null)
            {
                return View(product);
            }
            else
            {
                return View("GetAllProduct");
            }
        }
        [Authorize(Roles = "Admin,Employee,Buyer")]
        public ActionResult AddProduct()
        {
            ViewBag.KeyWordList = KeywordManager.GetSelectList(null);
            ViewBag.SupplierList = SupplierManager.GetSelectList(null);
            ViewBag.SubCategorieList = SubCategorieManager.GetSelectList(null);
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddProduct(Product product, HttpPostedFileBase upload)
        {
            ViewBag.KeyWordList = KeywordManager.GetSelectList(null);
            ViewBag.SupplierList = SupplierManager.GetSelectList(null);
            ViewBag.SubCategorieList = SubCategorieManager.GetSelectList(null);
            Product p = ProductManager.GetByName(product);
            if (p==null)
            {
                try
                {
                    if (ModelState.IsValid)
                    {
                        if (upload != null && upload.ContentLength > 0)
                        {
                            var avatar = new File
                            {
                                FileName = System.IO.Path.GetFileName(upload.FileName),
                                FileType = FileType.Avatar,
                                ContentType = upload.ContentType
                            };
                            using (var reader = new System.IO.BinaryReader(upload.InputStream))
                            {
                                avatar.Content = reader.ReadBytes(upload.ContentLength);
                            }
                            product.Files = new List<File> { avatar };
                        }
                        int nb = 0;
                        nb = ProductManager.Add(product);
                        return RedirectToAction("Products");
                    }

                }
                catch (RetryLimitExceededException /* dex */)
                {
                    //Log the error (uncomment dex variable name and add a line here to write a log.
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
                }

                return View(product);
            }
            else
            {
                return View(product);
            }
            
        }
    }
}

FindIt/Controllers/SupplierController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FindIt.Models.Manager;
using FindIt.Models.Entities;

namespace FindIt.Controllers
{
    [Authorize(Roles = "Admin,Employee,Buyer")]
    public class SupplierController : Controller
    {

        public ActionResult Index()
        {
            List<Supplier> list = SupplierManager.GetAll();
            return View(list);
        }

        public ActionResult Details(int id)
        {
            Supplier s = SupplierManager.GetById(id);
            return View(s);
        }

        public ActionResult Create(int id)
        {
            Supplier s = new Supplier();
            s.AddressId = id;
            return View(s);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Supplier s)
        {
            if (ModelState.IsValid)
            {
                SupplierManager.Add(s);
                return RedirectToAction("Index", "Supplier");
            }
            else
            {
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            Supplier s = SupplierManager.GetById(id);
            return View(s);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Supplier s)
        {
            if (ModelState.IsValid)
            {
                Supplier supplier = new Supplier();
                supplier.Id = s.Id;
                supplier.Name = s.Name;
                supplier.Phone = s.Phone;
                supplier.Products = s.Products;
                supplier.AddressId = s.AddressId;
                supplier.Address = s.Address;
                supplier.ContactRessource = s.ContactRessource;
                supplier.Description = s.Description;
                supplier.Email = s.Email;
                SupplierManager.Modify(s);
                return RedirectToAction("Index", "Supplier");
            }
            else
            {
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            SupplierManager.Delete(id);
            return RedirectToAction("Index", "Supplier");
        }
    }
}

FindIt/Views/Supplier/Create.cshtml
@using FindIt.Models.Entities
@using FindIt.Models.Manager
@model Supplier

@{
    ViewBag.Title = "Create";
    string labelHtmlClass = "control-label col-md-2";
    string inputHtmlClass = "form-control";
}

<h2>Supplier Add</h2>

@using (Html.BeginForm("Create", "Supplier", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()
    @Html.HiddenFor(m => m.AddressId)

    <div class="form-horizontal">

        <div class="form-group">
            @Html.LabelFor(m => m.Name, new { @class = labelHtmlClass })
            @Html.TextBoxFor(m => m.Name, new { @class = inputHtmlClass })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Description, new { @class = labelHtmlClass })
            @Html.TextBoxFor(m => m.Description, new { @class = inputHtmlClass })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Email, new { @class = labelHtmlClass })
            @Html.TextBoxFor(m => m.Email, new { @class = inputHtmlClass })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Phone, new { @class = labelHtmlClass })
            @Html.TextBoxFor(m => m.Phone, new { @class = inputHtmlClass })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.ContactRessource, new { @class = labelHtmlClass })
            @Html.TextBoxFor(m => m.ContactRessource, new { @class = inputHtmlClass })
        </div>

        <div class="form-group">
            <div class="col-md-offset-2">
                <input type="submit" value="submit" />
            </div>
        </div>
    </div>
}

FindIt/Views/Supplier/Details.cshtml
@using FindIt.Models.Entities
@using FindIt.Models.Manager
@model Supplier
@{
    ViewBag.Title = "Details";
    Address address = AddressManager.GetById(Model.AddressId);
    Province province = ProvinceManager.GetById(address.ProvinceId);
    Country country = CountryManager.GetById(province.CountryId);
    List<Product> listProduct = ProductManager.GetAllBySupplierId(Model.Id);
}

<h2>SupplierDetails</h2>


<table class="table">
    @Html.HiddenFor(m => m.Id);
    <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Address</th>
        <th>City</th>
        <th>Province/State</th>
        <th>Country</th>
        <th>Phone</th>
        <th>Contact tRessource</th>
        <th>Email</th>
    </tr>

    <tr>
        <td>@Model.Name</td>
        <td>@Model.Description</td>
        <td>@address.No @address.Street @address.PostalCode</td>
        <td>@address.City</td>
        <td>@province.Name</td>
        <td>@country.Name</td>
        <td>@Model.Phone</td>
        <td>@Model.ContactRessource</td>
        <td>@Model.Email</td>
    </tr>
</table>
<h3>Products of the Supplier @Model.Name</h3>
<table class="table">
    <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>
        <th>Quantity</th>
    </tr>
    @foreach (Product product in listProduct)
    {
        
        <tr>
            <td>@product.Name</td>
            <td>@product.Description</td>
            <td>@product.Price</td>
            <td>@product.Qty</td>
            <td>
                @Html.ActionLink("Edit", "Edit", "Product", new { id = product.Id }, new { @class = "btnDetails" })

                @{if (User.IsInRole("Admin"))
                {
                    @Html.ActionLink("Delete", "Delete", "Product", new { id = product.Id }, new { @class = "btnDelete" })
                }
                }
            </td>
        </tr>
    }
</table>

@Html.ActionLink("Back", "Index")

@section scripts{
    <script>
        $(document).ready(function () {
            $('.btnDelete').click(function () {
                return confirm("Are You certain you wish to delete this Product?");
            });
        });
    </script>
}

FindIt/Views/Supplier/Edit.cshtml
@using FindIt.Models.Entities
@using FindIt.Models.Manager
@model Supplier
@{
    ViewBag.Title = "Edit";
    string labelHtmlClass = "control-label col-md-2";
    string inputHtmlClass = "form-control";
}

<h2>SupplierEdit</h2>

@using (Html.BeginForm("Edit", "Supplier", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()
    @Html.HiddenFor(m => m.Id);
    @Html.HiddenFor(m => m.AddressId);

    <div class="form-horizontal">

        <div class="form-group">
            @Html.LabelFor(m => m.Name, new { @class = labelHtmlClass })
            @Html.TextBoxFor(m => m.Name, new { @class = inputHtmlClass })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Description, new { @class = labelHtmlClass })
            @Html.TextBoxFor(m => m.Description, new { @class = inputHtmlClass })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Email, new { @class = labelHtmlClass })
            @Html.TextBoxFor(m => m.Email, new { @class = inputHtmlClass })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Phone, new { @class = labelHtmlClass })
            @Html.TextBoxFor(m => m.Phone, new { @class = inputHtmlClass })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.ContactRessource, new { @class = labelHtmlClass })
            @Html.TextBoxFor(m => m.ContactRessource, new { @class = inputHtmlClass })
        </div>

        @Html.ActionLink("Edit Supplier's Address", "Edit", "Address", new { id = @Model.AddressId, supplierId = @Model.Id },null)

        <div class="form-group">
            <div class="col-md-offset-2">
                <input type="submit" value="submit" />
            </div>
        </div>
    </div>
}

FindIt/Views/Supplier/Index.cshtml
@using FindIt.Models.Entities
@using FindIt.Models.Manager
@model IEnumerable<Supplier>
@{
    ViewBag.Title = "Index";
}

<h2>Supplier Index</h2>

@Html.ActionLink("Add Supplier", "Create","Address")

<table class="table">
    <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Country</th>
        <th>Email</th>
    </tr>

    @foreach (Supplier s in Model)
    {
        Address address = AddressManager.GetById(s.AddressId);
        Province province = ProvinceManager.GetById(address.ProvinceId);
        Country country = CountryManager.GetById(province.CountryId);
        <tr>
            <td>@s.Name</td>
            <td>@s.Description</td>
            <td>@country.Name</td>
            <td>@s.Email</td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = s.Id })
                @Html.ActionLink("Details", "Details", new { id = s.Id })

                @{if (User.IsInRole("Admin"))
                {
                    @Html.ActionLink("Delete", "Delete", new { id = s.Id }, new { @class = "btnDelete" })
                }
                }
            </td>
        </tr>
    }
</table>


@section scripts{
    <script>
        $(document).ready(function () {
            $('.btnDelete').click(function () {
                return confirm("Are You certain you wish to delete this Supplier");
            });
        });
    </script>
}