FindIt/Models/Entities/CommandeClient.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FindIt.Models.Entities
{
    public class CommandeClient
    {
        public int Id { get; set; }
        public DateTime DateCommande { get; set; }
        public string ClientId { get; set; }
        public virtual ApplicationUser Client { get; set; }
        public int DeliveryAddressId { get; set; }
        public virtual Address DeliveryAddress { get; set; }
        public virtual ICollection<EntryCommandeClient> EntryCommandeClient { get; set; }
        //Permet d'arrêter de suivre la commande dans l'historique de commande d'un client (demandé par le client)
        //Ainsi il peut éliminer (visuellement) les commandes
        public bool isTrack { get; set; }

        //Par défaut, lorsqu'une commande est créé, elle est suvi par l'utilisateur
        public CommandeClient() {
            isTrack = true;
        }
    }
}

FindIt/Controllers/CommandeClientController.cs
using FindIt.Models.Entities;
using FindIt.Models.Manager;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FindIt.Controllers
{
    [Authorize]
    public class CommandeClientController : Controller
    {
        // GET: CommandClient
        public ActionResult Index()
        {
            ViewBag.CommandeClient = CommandeClientManager.GetAllFor(IdentityManager.GetByUser(User).Id);
            return View();
        }

        [Authorize(Roles="Admin")]
        public ActionResult All(Filtre filtre) {
            ViewBag.CommandeClient = CommandeClientManager.GetAllFor(IdentityManager.GetByUser(User).Id, filtre);
            return View(filtre);
        }


        public ActionResult Delete(int id) {
            CommandeClient commandeClient = CommandeClientManager.GetById(id);
            
            //Si la commandeClient existe et que l'utilisateur est propriétaire de la commande a supprimé
            if (commandeClient != null && commandeClient.ClientId == IdentityManager.GetByUser(User).Id) {
                CommandeClientManager.StopTracking(commandeClient);
            }
            return Index();
        }

        [Authorize(Roles = "Admin")]
        public ActionResult DeleteFromAdmin(int id) {
            CommandeClientManager.Delete(id);
            return All(null);
        }
    }
}

FindIt/Views/CommandeClient/All.cshtml
@using FindIt.Models.Entities
@model Filtre
@{
    ViewBag.Title = "All";
    ICollection<CommandeClient> commandeClients = ViewBag.CommandeClient;
}

<h2>Historique des commandes</h2>
@using (@Html.BeginForm("index", "CommandeClient", FormMethod.Post, new { @class = "form-horizontal" })) {
<div class="form-group">
    <div class="col-md-4">
        <div class="input-group">
            <span class="input-group-addon">Nom d'utilisateur</span>
            @Html.TextBoxFor(m => m.Username, new { @class = "form-control" })
        </div>
    </div>
    <div class="col-md-4">
        <div class="input-group">
            <span class="input-group-addon">Date Min.</span>
            @Html.TextBoxFor(m => m.MinimumDate, new { @class = "form-control", type = "date" })
        </div>
    </div>
    <div class="col-md-4">
        <div class="input-group">
            <span class="input-group-addon">Date Max.</span>
            @Html.TextBoxFor(m => m.MaximumDate, new { @class = "form-control", type = "date" })
        </div>
    </div>
</div>
<div class="form-group text-center">
    <input type="submit" class="btn btn-primary" value="Lancez la recherche" />
</div>
}

@if (commandeClients != null && commandeClients.Count > 0) {
    <table class="table">
        <tr>
            <th>N°</th>
            <th>Utilisateur</th>
            <th>Date</th>
            <th>Opération</th>
        </tr>
        @if (commandeClients != null && commandeClients.Count > 0) {
            foreach (CommandeClient cc in commandeClients) {
                <tr>
                    <td>@cc.Id</td>
                    <td>@cc.Client.UserName</td>
                    <td>@cc.DateCommande</td>
                    <td>
                        @Html.ActionLink("Détails", "Details", new { Id = cc.Id }, new { @class = "btn btn-default" })
                        @Html.ActionLink("Supprimer", "Delete", new { Id = cc.Id }, new { @class = "btn btn-default" })
                    </td>
                </tr>
            }
        }
    </table>
}
else {
    <div class="alert alert-info">
        Il ne figure aucune commande dans l'historique.
    </div>
}

FindIt/Views/CommandeClient/Index.cshtml
@using FindIt.Models.Entities
@model Filtre
@{
    ViewBag.Title = "Index";
    ICollection<CommandeClient> commandeClients = ViewBag.CommandeClient;
}

<h2>Historique des commandes</h2>
@if (commandeClients != null && commandeClients.Count > 0) {
    <table class="table">
        <tr>
            <th>N°</th>
            <th>Date</th>
            <th>Opération</th>
        </tr>
        @if (commandeClients != null && commandeClients.Count > 0) {
            foreach (CommandeClient cc in commandeClients) {
        <tr>
            <td>@cc.Id</td>
            <td>@cc.DateCommande</td>
            <td>
                @Html.ActionLink("Détails", "Details", new { Id = cc.Id }, new { @class = "btn btn-default" })
                @Html.ActionLink("Supprimer", "Delete", new { Id = cc.Id }, new { @class = "btn btn-default" })
            </td>
        </tr>
            }
        }
    </table>
   
}
else {
    <div class="alert alert-info">
        Il ne figure aucune commande dans l'historique.
    </div>
}