FindIt/Models/Entities/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;
using FindIt.Models.Entities;

namespace FindIt.Models.Entities
{
    public class Product
    {
        public int Id { get; set; }
        [Required]
        [MinLength(4, ErrorMessage = "un minimum de 4 caratere pour votre produit")]
        public string Name { get; set; }

        [Required]
        [MinLength(15, ErrorMessage = "un minimum de 15 caratere pour votre produit")]
        public string Description { get; set; }

        [Required]
        [Range(0, 1000000000000000, ErrorMessage = "un double compris entre 0 et 1000000000000000 ")]
        public double Price { get; set; }
        public String Photo { get; set; }
        public int Qty { get; set; }
        public virtual ICollection<Keyword> Keyword { get; set; }
        public virtual ICollection<Supplier> Supplier { get; set; }

        public virtual SubCategorie SubCategorie { get; set; }
        public Nullable<int> SubCategorieID { get; set; }


        public virtual ICollection<File> Files { get; set; }

        [NotMapped]
        public List<int> SelectedItemKeyWordIds { get; set; }

        [NotMapped]
        public MultiSelectList KeyWordItems { get; set; }

        [NotMapped]
        public List<int> SelectedItemSupplierIds { get; set; }

        [NotMapped]
        public MultiSelectList SupplierItems { get; set; }
    }
}

FindIt/Controllers/CommandeSupplierController.cs
using FindIt.Models.Entities;
using FindIt.Models.Manager;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace FindIt.Controllers
{
    public class CommandeSupplierController : Controller
    {
        // GET: CommandeSupplier
        public ActionResult Index()
        {
            List<CommandeSupplier> listCommandeSupplier = CommandeSupplierManager.GetAll();
            return View(listCommandeSupplier);
        }

        public ActionResult Add()
        {
            ViewBag.SupplierList = SupplierManager.GetSelectListItem(null);
            string idUserCurrent = User.Identity.GetUserId();
            return View();
        }

        public ActionResult Details(int id)
        {
            CommandeSupplier cs = CommandeSupplierManager.GetById(id);
            List<EntryCommandeSupplier> listEntryCommandeSupplier = EntryCommandeSupplierManager.GetByCommandeID(id);
            Address addresse = AddressManager.GetByCommandeID(id);
            cs.EntryCommandeSupplier = listEntryCommandeSupplier;
            cs.Supplier.Address = addresse;
            if (cs != null)
            {
                return View(cs);
            }
            else
            {
                return View("Index");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(CommandeSupplier commande)
        {
            ViewBag.SupplierList = SupplierManager.GetSelectListItem(null);
            string idUserCurrent = User.Identity.GetUserId();
            DateTime date = DateTime.Now;
            
            if (ModelState.IsValid)
            {
                commande.EmployeeId = idUserCurrent;
                commande.DateCommande = date;
                int nb = 0;
                nb = CommandeSupplierManager.Add(commande);
                return RedirectToAction("Index");
            }
            else
            {
                return View(commande);
            }

        }

        public ActionResult AddEntry()
        {
            List<Supplier> listSupplier = SupplierManager.GetAll();
            ViewBag.SupplierList = SupplierManager.GetSelectListItem(null);
            ViewBag.ProductList = ProductManager.GetSelectListItem(null);
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddEntry(EntryCommandeSupplier entry)
        {
            CommandeSupplier cs = CommandeSupplierManager.GetById(entry.Id);
            Supplier supplier = SupplierManager.GetByCommande(entry.Id);
            //ViewBag.SelectedSupplierID = KeyNotFoundException;
            ViewBag.SupplierList = SupplierManager.GetSelectListItem(null);
            ViewBag.ProductList = ProductManager.GetSelectListItem(null);

            if (ModelState.IsValid)
            {
                entry.CommandeSupplierId = entry.Id;
                
                int nb = 0;
                nb = EntryCommandeSupplierManager.Add(entry);
                return RedirectToAction("Add");
            }
            else
            {
                return View(entry);
            }
        }
    }
}

FindIt/Controllers/CommentController.cs
using FindIt.Models.Entities;
using FindIt.Models.Manager;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FindIt.Controllers
{
    public class CommentController : Controller
    {
        // GET: Comment
        public ActionResult Index()
        {
            return View();
        }
        [Authorize]
        public ActionResult Add(Comment comment)
        {
            if (Request.Form["CommentId"] != null)
                comment.Id = Int32.Parse(Request.Form["CommentId"]);
            else
                comment.Id = 0;

            if (User.Identity.IsAuthenticated)
            {
                if (ModelState.IsValid)
                {
                    if (RatingManager.GetUserRating(comment.ApplicationUserId, comment.ProductId) != null)
                    {
                        if (comment.Id != 0)
                        {
                            
                            CommentManager.Modify(comment);
                        }
                        else
                        {
                            CommentManager.Add(comment);
                        }
                        //   ModelState.AddModelError("comments", "Ecrivez un commentaire avant d'envoyer");
                        TempData["MessageErreur"] = "";
                    }
                    else
                    {
                        TempData["ErreurRating"] = "vous devez donnez une note avant de commenter";
                    }
                }
                else
                {
                    TempData["MessageErreur"] = "Ecrivez un commentaire avant d'envoyer";
                }
            }
            else
            {
                TempData["MessageErreur"] = "Vous devez vous connectez pour commenter ce produit";
            }
            return RedirectToAction("Details", "product", new { id = comment.ProductId });
        }
        public ActionResult Delete(int commentid, int produitid)
        {
            CommentManager.Delete(commentid);
            return RedirectToAction("Details", "product", new { id = produitid });
        }
    }
}

FindIt/Controllers/ProductController.cs
using FindIt.Models;
using FindIt.Models.Entities;
using FindIt.Models.Manager;
using FindIt.Models.Manager;
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace FindIt.Controllers
{
    [AllowAnonymous]
    public class ProductController : Controller
    {

        public ActionResult Delete3(int commentid, int produitid)
        {
            CommentManager.Delete(commentid);
            return RedirectToAction("Details", "product", new { id = produitid });
        }
        public ActionResult Products( int? page)
        {
            List<Product> allProduct = ProductManager.GetAll();
            int pageSize = 8;
            int pageNumber = (page ?? 1);
            return View(allProduct.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Index()
        {
            return View();
        }
        // GET: Produit
        //TODO A revoir remplacer la liste de categori par vue partial
        public ActionResult GetListCategoriePartialView()
        {
            List<MainCategories> listCategories = MainCategoriesManager.GetAll();
            return PartialView(listCategories);
        }


        public ActionResult GetProductByCategorieParitalView(int id, int? page)
        {
            List<Product> listProduct = ProductManager.GetByCategorieId(id);

            TempData["subCategories"] = SubCategorieManager.GetByIdCategorie(id);
            
            int pageSize = 8;
            int pageNumber = (page ?? 1);
            return View(listProduct.ToPagedList(pageNumber, pageSize));

        }
        public ActionResult GetProductBySubCategorieParitalView(int id)
        {
            List<Product> listProduct = ProductManager.GetByIdSubCategorie(id);
            if (listProduct != null)
            {
          //      SubCategorie sub = SubCategorieManager.GetById(listProduct.FirstOrDefault().SubCategorieID);
                SubCategorie sub = SubCategorieManager.GetById(id); 
                if(sub != null)
                    TempData["subCategories"] = SubCategorieManager.GetByIdCategorie(sub.MainCategoriesId);
            }
            return View("GetProductByCategorieParitalView", listProduct.ToPagedList( 1, 8));
        }
        // getAll Product by Categorie
        public ActionResult GetProductByCategorie(int id)
        {
            List<Product> listProduct = ProductManager.GetByCategorieId(id);
            TempData["subCategories"]
                = SubCategorieManager.GetByIdCategorie(id);
            return View("GetAllProduct", listProduct);
        }

        //getAll product by name or KeyWord

        public ActionResult GetProductByNameOrKeyWord(string name)
        {
            List<Product> listProduct = ProductManager.GetByNameOrKeyWord(name);
            return View("GetProductByNameOrKeyWord", listProduct);
        }


        public ActionResult GetAllProduct()
        {
            List<Product> allProduct = ProductManager.GetAll();
            return View(allProduct);
        }

        [Authorize(Roles="Admin,Employee,Buyer")]
        public ActionResult AddKeyWord(string key)
        {
            Keyword keyword = new Keyword { Name = key };
            int nb = KeywordManager.Add(keyword);
            if (nb > 0)
            {

                TempData["msg"] = "L'ajout est bien ajoute";
            }
            else
            {
                TempData["msg"] = "mot cle deja existe";
            }
            
            ViewBag.KeyWordList = KeywordManager.GetSelectList(null);
            return View();
        }

        [Authorize(Roles = "Admin,Employee,Buyer")]
        public ActionResult Edit(int id)
        {
            ViewBag.KeyWordList = KeywordManager.GetSelectList(null);
            ViewBag.SupplierList = SupplierManager.GetSelectList(null);
            ViewBag.SubCategorieList = SubCategorieManager.GetSelectList(null);
            Product product = ProductManager.GetById(id);
            if (product != null)
            {
                return View(product);
            }
            else
            {
                return RedirectToAction("GetAllProduct");
            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Product product, HttpPostedFileBase upload)
        {
            Product pro = ProductManager.GetById(product.Id); 
            if (ModelState.IsValid)
            {
                if (upload != null && upload.ContentLength > 0)
                {
                    File ff = pro.Files.Where(p => p.ProductId == pro.Id).FirstOrDefault();
                    if (pro.Files.Any(f => f.FileType == FileType.Avatar))
                    {

                        FileManager.Delete(ff);
                    }
                    var avatar = new File
                    {
                        FileName = System.IO.Path.GetFileName(upload.FileName),
                        FileType = FileType.Avatar,
                        ContentType = upload.ContentType
                    };
                    using (var reader = new System.IO.BinaryReader(upload.InputStream))
                    {
                        avatar.Content = reader.ReadBytes(upload.ContentLength);
                    }
                    product.Files = new List<File> { avatar };
                }
                ProductManager.Edit(product);
                ModelState.Clear();
                return RedirectToAction("Products");
            }
            else
            {
                ViewBag.KeyWordList = KeywordManager.GetSelectList(null);
                ViewBag.SupplierList = SupplierManager.GetSelectList(null);
                ViewBag.SubCategorieList = SubCategorieManager.GetSelectList(null);
                return View(product);
            }
        }

        [Authorize(Roles = "Admin,Employee,Buyer")]
        public ActionResult Delete(int id)
        {
            ProductManager.Delete(id);
            return RedirectToAction("GetAllProduct");
        }


        public ActionResult Details(int id)
        {
            Product product = ProductManager.GetById(id);
            if (product != null)
            {
                return View(product);
            }
            else
            {
                return View("GetAllProduct");
            }
        }
        [Authorize(Roles = "Admin,Employee,Buyer")]
        public ActionResult AddProduct()
        {
            ViewBag.KeyWordList = KeywordManager.GetSelectList(null);
            ViewBag.SupplierList = SupplierManager.GetSelectList(null);
            ViewBag.SubCategorieList = SubCategorieManager.GetSelectList(null);
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddProduct(Product product, HttpPostedFileBase upload)
        {
            ViewBag.KeyWordList = KeywordManager.GetSelectList(null);
            ViewBag.SupplierList = SupplierManager.GetSelectList(null);
            ViewBag.SubCategorieList = SubCategorieManager.GetSelectList(null);
            Product p = ProductManager.GetByName(product);
            if (p==null)
            {
                try
                {
                    if (ModelState.IsValid)
                    {
                        if (upload != null && upload.ContentLength > 0)
                        {
                            var avatar = new File
                            {
                                FileName = System.IO.Path.GetFileName(upload.FileName),
                                FileType = FileType.Avatar,
                                ContentType = upload.ContentType
                            };
                            using (var reader = new System.IO.BinaryReader(upload.InputStream))
                            {
                                avatar.Content = reader.ReadBytes(upload.ContentLength);
                            }
                            product.Files = new List<File> { avatar };
                        }
                        int nb = 0;
                        nb = ProductManager.Add(product);
                        return RedirectToAction("Products");
                    }

                }
                catch (RetryLimitExceededException /* dex */)
                {
                    //Log the error (uncomment dex variable name and add a line here to write a log.
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
                }

                return View(product);
            }
            else
            {
                return View(product);
            }
            
        }
    }
}

FindIt/Views/Product/AddProduct.cshtml
@using FindIt.Models.Entities
@using FindIt.Models.Manager


@model Product

@{
    ViewBag.Title = "AddProduct";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>

<h2>AddProduct</h2>

@using (Html.BeginForm("AddProduct", "Product", null, FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Ajout des produuit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Qty, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Qty, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>
        
        
        <div class="form-group" id="ajouterKeyWord" hidden="hidden">
            @Html.LabelFor(model => model.Keyword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                <input type="text" name="keyword" id="key" />
                <input type="button" value="Ajouter mot cle" id="AddKeyWord" class="btn btn-success"  />

            </div>
        </div>

        
            <div class="form-group" id="listKeyWord">
                @Html.LabelFor(model => model.Keyword, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @*@Html.Label("KeyWord", new { @class = "control-label col-md-2" })*@
                    @Html.ListBoxFor(m => m.SelectedItemKeyWordIds, @ViewBag.KeyWordList as MultiSelectList,
      new { @class = "form-control" })
                </div>
                <div>
                    <input type="button" value="Ajouter" id="ajouter" class="btn btn-success" />
                </div>

            </div>
        <span>@ViewData["msg"]</span>
        <span class="btn-danger">@TempData["msg"] </span>
        <div class="form-group">
            @Html.LabelFor(model => model.Supplier, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.ListBoxFor(key => key.SelectedItemSupplierIds, @ViewBag.SupplierList as MultiSelectList,
      new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.SubCategorieID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.DropDownListFor(m => m.SubCategorieID, @ViewBag.SubCategorieList as IEnumerable<SelectListItem>,
          new { @class = "form-control" })
            </div>
        </div>
        @* for upload picture *@
        <div class="form-group">
            @Html.Label("Avatar", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="Avatar" name="upload" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Tous les Produit", "Details")
</div>

<script>
    $(document).ready(function () {

        $('#ajouter').click(function () {
            $('#ajouterKeyWord').show();
            $('#listKeyWord').hide();
        });


        var globalRootBaseAjaxUrl = '@VirtualPathUtility.ToAbsolute("~/")';

        $("#AddKeyWord").click(function () {
            var url = globalRootBaseAjaxUrl + "Product/AddKeyWord";
            var id = $("#key").val();
            $.post(url, { key: id }, function (data) {

                $("#listKeyWord").html(data);

            });
            $('#ajouterKeyWord').hide();
            $('#listKeyWord').show();
        })
    });
</script>


@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FindIt/Views/Product/Edit.cshtml
@using FindIt.Models.Entities
@model Product

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Product", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" id="listKeyWord">
            @Html.LabelFor(model => model.Keyword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.ListBoxFor(m => m.SelectedItemKeyWordIds, @ViewBag.KeyWordList as MultiSelectList,
      new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Supplier, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.ListBoxFor(key => key.SelectedItemSupplierIds, @ViewBag.SupplierList as MultiSelectList,
      new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.SubCategorieID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.DropDownListFor(m => m.SubCategorieID, @ViewBag.SubCategorieList as IEnumerable<SelectListItem>,
          new { @class = "form-control" })
            </div>
        </div>

        @* Change product picture *@
        @if (Model.Files.Any(f => f.FileType == FileType.Avatar))
        {
            <div class="form-group">
                <span class="control-label col-md-2"><strong>Current Avatar</strong></span>
                <div class="col-md-10">
                    <img src="~/File?id=@Model.Files.First(f => f.FileType == FileType.Avatar).FileId" alt="avatar" />
                </div>
            </div>
        }

        <div class="form-group">
            @Html.Label("Avatar", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="Avatar" name="upload" />
            </div>
        </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
}


<div>
    @Html.ActionLink("Tous les Produit", "GetAllProduct")
</div>

FindIt/Views/Product/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<!-- ================ -->
<section class="main-container padding-bottom-clear">
    <div class="container">
        <div class="row">
            <!-- main start -->
            <!-- ================ -->
            <div class="main col-md-12">
                <div class="row">

                    @using (Html.BeginForm())
                    {
                        <div class="col-md-4 col-sm-6">
                            <div class="ph-20 feature-box text-center object-non-visible" data-animation-effect="fadeInDownSmall" data-effect-delay="300">
                                <span class="icon large default-bg circle"><i class="fa fa-search"></i></span>
                                <h3>voir tous les produits</h3>
                                <div class="separator clearfix"></div>
                                <p class="text-muted">Pour voir toute la liste des produit c'est ici !.</p>
                                <a href="@Url.Action("Products", "Product")">Tous les produits <i class="pl-5 fa fa-angle-double-right"></i></a>
                            </div>
                        </div>
                    }
                    @using (Html.BeginForm())
                    {
                        
                        <div class="col-md-4 col-sm-6">
                            <div class="ph-20 feature-box text-center object-non-visible" data-animation-effect="fadeInDownSmall" data-effect-delay="100">
                                <span class="icon large default-bg circle"><i class="fa fa-plus"></i></span>
                                <h3>Ajouter un produit</h3>
                                <div class="separator clearfix"></div>
                                <p class="text-muted">Si vous voulez Ajoutez un produit c'est ici.</p>

                                <a href="@Url.Action("AddProduct", "Product")">Ajouter Produit<i class="pl-5 fa fa-angle-double-right"></i></a>

                            </div>
                        </div>
                    }
                    @using (Html.BeginForm())
                    {
                        <div class="col-md-4 col-sm-6">
                            <div class="ph-20 feature-box text-center object-non-visible" data-animation-effect="fadeInDownSmall" data-effect-delay="200">
                                <span class="icon large default-bg circle"><i class="fa fa-plus"></i></span>
                                <h3>Commande fournisseur</h3>
                                <div class="separator clearfix"></div>
                                <p class="text-muted">Pour ajouter des commandes c'est ICI!!!.</p>
                                <a href="@Url.Action("Index", "CommandeSupplier")">Ajouter une commande<i class="pl-5 fa fa-angle-double-right"></i></a>
                            </div>
                        </div>
                    }

                    @using (Html.BeginForm())
                    {
                        <div class="col-md-4 col-sm-6">
                            <div class="ph-20 feature-box text-center object-non-visible" data-animation-effect="fadeInDownSmall" data-effect-delay="300">
                                <span class="icon large default-bg circle"><i class="fa fa-search"></i></span>
                                <h3>Chercher un produit</h3>
                                <div class="separator clearfix"></div>
                                <p class="text-muted">Pour chercher un produit, modfier un produit, supprimer un ptoduit c'est la !.</p>
                                <a href="@Url.Action("GetAllProduct", "Product")">Chercher Product <i class="pl-5 fa fa-angle-double-right"></i></a>
                            </div>
                        </div>
                    }



                    <div class="clearfix visible-md"></div>

                </div>
            </div>
            <!-- main end -->
        </div>
    </div>
</section>
<!-- main-container end -->

FindIt/Views/Product/_AddKeyWord.cshtml
@using FindIt.Models.Entities
@model Keyword

@using (Html.BeginForm("AddKeyWord", "")) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Keyword</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.ListBoxFor(m => m.Name, @ViewBag.KeyWordList as MultiSelectList,
      new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FindIt/Views/Product/_GetListCategoriePartialView.cshtml
@using FindIt.Models.Entities
@using FindIt.Models.Manager
@using FintIt.Models.Manager

@model IEnumerable<FindIt.Models.Entities.MainCategories>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        
        <th></th>
    </tr>
   @foreach (MainCategories m in MainCategoriesManager.GetAll())
   {
        @Html.ActionLink(m.Name, "Edit", new { id = m.Id })
   }
@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>